-
    name: Trip1
    measure_interval: 15
    distances: [!!float 0, 0.19, 0.5, 0.75, !!float 1, 1.25, 1.5, 1.75, !!float 2, 2.25]
-
    name: Trip2
    measure_interval: 20
    distances: [!!float 0, 0.23, 0.46, 0.69, 0.92, 1.15, 1.38, 1.61]
-
    name: Trip3
    measure_interval: 12
    distances: [!!float 0, 0.11, 0.22, 0.33, 0.44, 0.65, 1.08, 1.26, 1.68, 1.89, 2.1, 2.31, 2.52, 3.25]
